### ISSUE TITLE
Having other people hear sounds from soundboard

### ISSUE THREAD

**Issue by hurnhu** [Wuzi/streamersb#2]
Is it possible to the sounds play so other in voice chat or in your game lobby can hear?

I've been looking into a solution for this in C#, until i found this repo which does a lot of what i wanted.

**Comment by hurnhu** [comment]
never mind, this is only possible in higher level languages

**Comment by Wuzi** [comment]
Yea, probably electron could do that, but i don't know how.
If you're only looking to use this feature, i use this: https://www.voicemod.net/
does what you want, tho it's not fully-free (or open source)

**Comment by hurnhu** [comment]
yeah im actually wanting to make that but free.
i dont use it, but i though itd be a fun project.
